/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file since it will be overwritten
// on running the dev server or build.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Indexes

const IndexRoute = createFileRoute('/')()

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface IndexRouteChildren {}

const IndexRouteWithChildren = IndexRoute._addFileChildren(
  {} as IndexRouteChildren
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteWithChildren
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteWithChildren
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteWithChildren
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// Import the lazy route tree
import { Route as IndexImport } from './routes/index'

// Create/Update Routes
const IndexLazyRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Assign route children
rootRoute._addFileChildren({
  IndexRoute: IndexLazyRoute,
})

export { rootRoute, IndexLazyRoute as IndexRoute }
